name: Deploy to WordPress.org
on:
  push:
    tags:
    - "*"
    branches:
    - master

jobs:
  deploy-plugin:
    name: Deploy Plugin
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: WordPress Plugin Deploy
      uses: actions/checkout@v1.5
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SLUG: repeater-entries-widget # optional, remove if GitHub repo name matches SVN slug, including capitalization
        VERSION: 1.5
        # This is a basic workflow to help you get started with Actions
