name: Deploy to WordPress.org
on:
  push:
    tags:
    - "*"
    branches:
    - master

jobs:
  tag:
    name: Deply Plugin
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: WordPress Plugin Deploy
      uses: actions/checkout@master
      with:
        repositories: zealousweb/repeater-entries-widget@master
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}